yes=ja
no=nein
Environments=Umgebungen
Environment=Umgebung
EditEnvironment=Umgebung bearbeiten
NewEnvironment=Neue Umgebung eingeben
active=aktiv
New=Neu
Save=Speichern
Cancel=Abbruch
Name=Name
AddRule=Neue Alarmregel
EditRule=Alarmregel bearbeiten
alertsFor=Alarme für Umgebung
Edit=Bearbeiten
Delete=Löschen
Alerts=Alarme
NewGroup=Neue Alarmgruppe
EditGroup=Alarmgruppe bearbeiten
none=keine
Summary=Titel
Description=Beschreibung
notActive=deaktiviert
rulesSize=Alarmregeln
