yes=ja
no=nein
Environments=Umgebungen
Environment=Umgebung
EditEnvironment=Umgebung bearbeiten
NewEnvironment=Neue Umgebung eingeben
active=aktiv
New=Neu
Save=Speichern
Cancel=Abbruch
Name=Name
AddRule=Neue Alarmregel
EditRule=Alarmregel bearbeiten
alertsFor=Alarme f�r Umgebung
Edit=Bearbeiten
Delete=L�schen
Alerts=Alarme
NewGroup=Neue Alarmgruppe
EditGroup=Alarmgruppe bearbeiten
none=keine
Summary=Titel
Description=Beschreibung
notActive=deaktiviert
rulesSize=Alarmregeln
MonitoredTargets=Beobachtete Ziele
AddMTLinuxServer=Neuer Linux Server
AddMTOracleDB=Neue Oracle Datenbank
AddMTPostgresDB=Neue PostgreSQL Datenbank
AddMTSite=Neue Site
EditMTLinuxServer=Linux server bearbeiten
EditMTOracleDB=Oracle Datenbank bearbeiten
EditMTPostgresDB=Edit PostgreSQL Datenbank bearbeiten
EditMTSite=Site bearbeiten
Host=Host
User=Benutzer
Password=Passwort
PathOptional=Pfad (optional)
Type=Typ
NewEnvironment=Neue Umgebung
OtcLabel=Ziel OTC Instanz
database=Datenbank
Options=Einstellungen
Close=Schließen
