yes=yes
no=no
active=active
New=New
EditEnvironment=Edit environment
Environment=Environment
Environments=Environments
NewEnvironment=Create environment
Save=Save
Cancel=Cancel
Name=Name
AddRule=Create alert rule
EditRule=Edit alert rule
alertsFor=Alerts for environment
Edit=Edit
Delete=Delte
Alerts=Alerts
NewGroup=Create alert group
EditGroup=Edit alert group
none=none
Summary=Summary
Description=Description
notActive=not active
rulesSize=Rules
