yes=yes
no=no
active=active
New=New
EditEnvironment=Edit environment
Environment=Environment
Environments=Environments
NewEnvironment=Create environment
Save=Save
Cancel=Cancel
Name=Name
AddRule=Create alert rule
EditRule=Edit alert rule
alertsFor=Alerts for environment
Edit=Edit
Delete=Delete
Alerts=Alerts
NewGroup=Create alert group
EditGroup=Edit alert group
none=none
Summary=Summary
Description=Description
notActive=not active
rulesSize=Rules
MonitoredTargets=Monitored targets
AddMTLinuxServer=Create Linux server
AddMTOracleDB=Create Oracle database
AddMTPostgresDB=Create PostgreSQL database
AddMTSite=Create site
EditMTLinuxServer=Edit Linux server
EditMTOracleDB=Edit Oracle database
EditMTPostgresDB=Edit PostgreSQL database
EditMTSite=Edit site
Host=Host
User=User
Password=Password
PathOptional=Path (optional)
Type=Type
NewEnvironment=Create environment
OtcLabel=target OTC instance
database=database
Options=Options
Close=Close
