yes=yes
no=no
active=active
New=New
EditEnvironment=Edit environment
Environment=Environment
Environments=Environments
NewEnvironment=Create environment
Save=Save
Cancel=Cancel
Name=Name
AddRule=Create alert rule
EditRule=Edit alert rule
alertsFor=Alerts for environment
Edit=Edit
Delete=Delete
Alerts=Alerts
NewGroup=Create alert group
EditGroup=Edit alert group
none=none
Summary=Summary
Description=Description
notActive=not active
rulesSize=Rules
MonitoredTargets=Monitored targets
AddMTLinuxServer=Create Linux server
AddMTOracleDB=Create Oracle database
AddMTPostgresDB=Create PostgreSQL database
AddMTSite=Create site
EditMTLinuxServer=Edit Linux server
EditMTOracleDB=Edit Oracle database
EditMTPostgresDB=Edit PostgreSQL database
EditMTSite=Edit site
MTLinuxServer=Linux server
MTOracleDB=Oracle database
MTPostgresDB=PostgreSQL database
MTSite=Site
Host=Host
User=User
Password=Password
PathOptional=Path (optional)
Type=Type
NewEnvironment=Create environment
OtcLabel=target OTC instance
database=database
Options=Options
Close=Close
DownloadConfig=Download configuration
UploadConfig=Upload configuration
CreateTag=Create Git tag
Customer=Customer
CustomerKey=Customer key
SelectBranch=Select branch
InstallOTC=Install OTC
CantDeleteEnvironment=The environment cannot be deleted because there are still monitored targets and/or alarm rules.
installOtelcolContribFailed=Installation of otelcol-contrib failed
typicalValue=typical value
otcStatus=OTC status
otcIsAlive=OTC is alive
otcNotRunning=OTC is not running
otcProcessId=OTC process ID
HealthCheck=Health check
exists=exists
notexist=doesn't exist
fileXNotFound=File $x not found
otcInfo=The OpenTelemetry Collector (OTC) runs within Hestia and collect or receive metrics, traces, and logs.
startOTC=Start OTC
killOTC=Kill OTC
otcDownloadUrl=OTC download source
taggen=tag with $t
